[package]
name = "opaque-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# shared-memory enabled for zenoh even if zenoh-c "shared-memory" feature is disabled. This is to make "std::mem::transmute" work for `ZSLice`
# zenoh = { version = "0.11.0-dev", git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "main", features = ["shared-memory", "unstable"], default-features = false }
zenoh = { path = "../../../zenoh/zenoh", features = [
    "shared-memory",
    "unstable",
], default-features = false }
zenoh-ext = { path = "../../../zenoh/zenoh-ext", features = ["unstable"] }
