[package]
name = "opaque-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
shared-memory = ["zenoh/shared-memory", "zenoh-ext/shared-memory"]
unstable = []
default = ["zenoh/default", "unstable", "shared-memory"]

[dependencies]
# shared-memory enabled for zenoh even if zenoh-c "shared-memory" feature is disabled. This is to make "std::mem::transmute" work for `ZSLice`
zenoh = { version = "0.11.0-dev", git = "https://github.com/ZettaScaleLabs/zenoh.git", branch = "fix_shm_async_api", features = ["unstable", "shared-memory"], default-features = false }
zenoh-ext = { version = "0.11.0-dev", git = "https://github.com/ZettaScaleLabs/zenoh.git", branch = "fix_shm_async_api", features = ["unstable", "shared-memory"] }
const_format = "0.2.32"
