name: Build (simple)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    # `cargo check` command here will use installed `nightly`
    # as it is set as an "override" for current directory
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose

    - name: Run rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make example
      run: make example
    - name: Gather artifacts
      run: |
        mkdir -p artifacts/zenoh-c/examples/zenoh artifacts/zenoh-c/examples/zenoh-net
        cp target/release/libzenohc.* artifacts/zenoh-c/
        cp target/release/z_* artifacts/zenoh-c/examples/zenoh
        cp target/release/zn_* artifacts/zenoh-c/examples/zenoh-net
        chmod +x artifacts/zenoh-c/examples/zenoh/*
        chmod +x artifacts/zenoh-c/examples/zenoh-net/*
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: zenoh-c-${{ matrix.os }}
        # Directory containing files to upload
        path: artifacts/zenoh-c
